# ------------------------------
# âš™ï¸ Configuration du portfolio GitHub Pages
# ------------------------------

title: "Alseny SACKO"
description: "Data Scientist & Machine Learning Engineer | IA GÃ©nÃ©rative & MLOps"
logo: "/images/photo/phot.jpg"
show_downloads: true

# ğŸ¨ ThÃ¨me GitHub Pages
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# ğŸ’¡ (Optionnel) Couleur principale du thÃ¨me
#theme: jekyll-theme-minimal
#remote_theme: pages-themes/merlot@v0.2.0
