title: "Alseny SACKO"
description: "Data Scientist spécialisé en MLOps et Intelligence Artificielle"
logo: "/images/photo/phot.jpg"
show_downloads: true
remote_theme: "pages-themes/minimal@v0.2.0"
plugins:
  - jekyll-remote-theme
